name: Website mirror

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
          
    - name: Open expanders (the details tag)
      run: |
        sed -i "s/<details><summary><strong>/<h2>/g" README.md
        sed -i "s/<\/strong> (click)<\/summary><p>/<\/h2>/g" README.md
        sed -i "s/<\/p><\/details>/<!--Quack-->/g" README.md
    
    - name: Rename readme to index
      run: mv README.md index.md
      
    - name: Add theme file
      run: |
        echo "theme: jekyll-theme-architect" > _config.yml
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: gh-pages publish
      with:
        branch: gh-pages
        folder: .

