name: Website mirror

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
          
    - name: Open expanders (the details tag)
      run: |
        # Expand spoilers & add headers
        sed -i "s/<details><summary><strong>/<h2>/g" README.md
        sed -i "s/<\/strong> (click)<\/summary><p>/<\/h2>/g" README.md
        sed -i "s/<\/p><\/details>/<!--Quack-->/g" README.md
        
        # Remove hrs
        sed -i "s/<hr>/<!--QuackQuack-->/g" README.md
        
        # Dark and light pictures to depend on the theme
        sed -i "s/#gh-light-mode-only\"/\" class=\"light-only\"/g" README.md
        sed -i "s/#gh-dark-mode-only\"/\" class=\"dark-only\"/g" README.md
        
        # Add styles
        echo '<style>' > beginning
        cat beginning >> README.md
        cat styles.css >> README.md
        echo '</style>' > end
        cat end >> README.md
    
    - name: Rename readme to index
      run: mv README.md index.md
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: gh-pages publish
      with:
        branch: gh-pages
        folder: .

